### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by UgaBugaBoo** [Illogicalll/VALORANT-Store-Checker#1]
It does not seem to work

`Traceback (most recent call last):
  File "C:\Users\Lenny_VEE\Desktop\main.py", line 73, in <module>
    asyncio.get_event_loop().run_until_complete(run('exmaple user name', 'my_secret_password'))
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Lenny_VEE\Desktop\main.py", line 54, in run
    skins = data['skinLevels']
KeyError: 'skinLevels'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000237EB6C83D0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000237EB6EA5C0>, 912.984), (<aiohttp.client_proto.ResponseHandler object at 0x00000237EB6EA920>, 914.843)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x00000237EB6EB0A0>, 914.421)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x00000237EB6EB580>, 916.203)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000237EB6C8A30>`

**Comment by Illogicalll** [comment]
I have updated that portion of the code and you no longer require an API key from riot to use the program, I have a feeling that might be where your error came from. If you like you can redownload/copy and paste the new code and try that. Let me know if the issue persists. Furthermore, if you are not located in Europe you may need to change the 'eu' part in the URL on line 48 from `https://pd.eu.a.pvp.net/store/v2/storefront/{user_id}` to either NA (North America), AP (Asia Pacific), KO (Korea)

**Comment by UgaBugaBoo** [comment]
> I have updated that portion of the code and you no longer require an API key from riot to use the program, I have a feeling that might be where your error came from. If you like you can redownload/copy and paste the new code and try that. Let me know if the issue persists. Furthermore, if you are not located in Europe you may need to change the 'eu' part in the URL on line 48 from `https://pd.eu.a.pvp.net/store/v2/storefront/{user_id}` to either NA (North America), AP (Asia Pacific), KO (Korea)

Yup, thanks it's now working properly

![image](https://user-images.githubusercontent.com/7885525/146158539-0f58d552-586b-4061-a5f2-c31a32dc4150.png)
